Repository VeritasTrial/ac215_VeritasTrial, pull requests merged in 2024-11, with the labels that each got.

#11 data-pipeline: fix typo in clean script
  src/data-pipeline/clean.py
Labels: data-pipeline

#9 app: init backend/frontend framework and docker compose
  .gitignore
  app/Makefile
  app/backend/Dockerfile
  app/backend/Pipfile
  app/backend/Pipfile.lock
  app/backend/localtyping.py
  app/backend/main.py
  app/backend/utils.py
  app/docker-compose.yaml
  app/frontend/.dockerignore
  app/frontend/.prettierignore
  app/frontend/Dockerfile
  app/frontend/eslint.config.js
  app/frontend/index.html
  app/frontend/package.json
  app/frontend/pnpm-lock.yaml
  app/frontend/public/veritastrial.svg
  app/frontend/src/App.tsx
  app/frontend/src/api.ts
  app/frontend/src/components/ChatCollapsibleHint.tsx
  app/frontend/src/components/ChatErrorMessage.tsx
  app/frontend/src/components/ChatInput.tsx
  app/frontend/src/components/ChatPanel.tsx
  app/frontend/src/components/ChatPort.tsx
  app/frontend/src/components/CopyButton.tsx
  app/frontend/src/components/ExternalLink.tsx
  app/frontend/src/components/FCClearHistoryButton.tsx
  app/frontend/src/components/FCDeleteChatButton.tsx
  app/frontend/src/components/FCSendButton.tsx
  app/frontend/src/components/FCTopKSelector.tsx
  app/frontend/src/components/Header.tsx
  app/frontend/src/components/MessageDocs.tsx
  app/frontend/src/components/MessageRetrieved.tsx
  app/frontend/src/components/RetrievePanel.tsx
  app/frontend/src/components/RetrievePanelCommandPalette.tsx
  app/frontend/src/components/Sidebar.tsx
  app/frontend/src/consts.ts
  app/frontend/src/main.tsx
  app/frontend/src/types.ts
  app/frontend/src/utils.ts
  app/frontend/src/vite-env.d.ts
  app/frontend/tsconfig.app.json
  app/frontend/tsconfig.json
  app/frontend/tsconfig.node.json
  app/frontend/vite.config.ts
  src/embedding-model/store.py
Labels: app

#15 ci: configure dependabot to update app dependencies
  .github/dependabot.yaml
Labels: ci

#18 ci: add build app workflow
  .github/workflows/build.yaml
Labels: ci

#20 ci: make dependabot update all (including indirect) dependencies
  .github/dependabot.yaml
  app/backend/Pipfile
  app/backend/Pipfile.lock
Labels: ci

#23 ci: initialize test and coverage workflow
  .github/workflows/test.yaml
  .gitignore
  app/Makefile
  app/backend/Dockerfile
  app/backend/Pipfile
  app/backend/Pipfile.lock
  app/backend/conftest.py
  app/backend/localtyping.py
  app/backend/main.py
  app/backend/test_main.py
  app/backend/test_utils.py
  app/backend/utils.py
  app/frontend/package.json
Labels: ci

#26 ci(test): extend backend test suite except for the chat endpoint
  app/backend/conftest.py
  app/backend/main.py
  app/backend/test_main.py
  app/backend/test_utils.py
Labels: ci

#22 data-pipeline: avoid null values in the first place
  src/data-pipeline/clean.py
  src/embedding-model/Pipfile
  src/embedding-model/Pipfile.lock
  src/embedding-model/store.py
Labels: data-pipeline

#29 ci: extend dependabot to also update the pipeline
  .github/dependabot.yaml
  src/embedding-model/Dockerfile
Labels: ci

#31 app: support chat history with chat sessions
  app/backend/conftest.py
  app/backend/localtyping.py
  app/backend/main.py
  app/backend/test_main.py
  app/frontend/src/api.ts
  app/frontend/src/types.ts
Labels: app

#13 app(ui/ux): add scroll-to-top and scroll-to-botton buttons
  app/frontend/src/components/ChatPanel.tsx
  app/frontend/src/components/FCScrollButtons.tsx
  app/frontend/src/components/RetrievePanel.tsx
  app/frontend/src/utils.ts
Labels: app
